### ISSUE TITLE
Missing matches in simple example

### ISSUE THREAD

**Issue by thekswenson** [nicolaprezza/r-index#5]
There seem to be missing matches in the following toy example.

```
=> cat test/fake0.txt
acgtaaaacgt
acgtataacgt

=> cat test/fake0_READS.txt
# number=2 length=5 file=/blah/blah forbidden=
taaaa
acgta
```

While the index building process  does not complain, the output of `ri-count` seems to be missing an occurrence.  Shouldn't it be `occ_t = 3`, since `acgta` matches twice and `taaaa` matches once?

```
=> r-index_nicolaprezza/build/ri-count test/fake0.txt.ri test/fake0_READS.txt
Loading r-index
searching patterns ...
50% done ...

1 average occurrences per pattern
Load time : 0 milliseconds
number of patterns n = 2
pattern length m = 5
total number of occurrences  occ_t = 2
Total time : 0 milliseconds
Search time : 0 milliseconds/pattern (total: 2 patterns)
Search time : 0 milliseconds/occurrence (total: 2 occurrences)
```

**Comment by nicolaprezza** [comment]
Hi, 

It looks like you are using the wrong input format. Patterns should be in [Pizza&Chili format](http://pizzachili.dcc.uchile.cl/experiments.html): all patterns should be concatenated. This input generates the correct output (at least, on my original branch):

=> cat test/fake0.txt
acgtaaaacgt
acgtataacgt

=> cat test/fake0_READS.txt
\# number=2 length=5 file=/blah/blah forbidden=
taaaaacgta


output: 

Loading r-index
searching patterns ...
50% done ...

1.5 average occurrences per pattern
Load time : 0 milliseconds
number of patterns n = 2
pattern length m = 5
total number of occurrences  occ_t = 3
Total time : 0 milliseconds
Search time : 0 milliseconds/pattern (total: 2 patterns)
Search time : 0 milliseconds/occurrence (total: 3 occurrences)



You can check the examples in folder datasets/ if you have other doubts on the input format. 

Nicola

**Comment by thekswenson** [comment]
I had checked the link you give to the Pizza&Chili page, and I don't see any _explicit_ mention of a file format there.  There is some file mentioned as the output of a program called `genpatterns`, and I suppose that may be the "Pizza&Chili" format you are referring to.  In the description of that output, I can read (with hindsight) "The <number> patterns then come one after the other without any separator" as meaning that there are <number> patterns _concatenated_ without any separator, but my first read of "one after the other" was that they came on separate lines.  Why not just say "concatenated" if that's what they mean?

Anyway, it may be worth just putting the file format on the readme.

So it looks like all the strings need to be the same length.  I guess I am supposed to pad the strings with some unique character, or is there another trick?

**Comment by nicolaprezza** [comment]
yes, the format is not well documented. genpatterns extracts random patterns of a fixed length from an input text and concatenates them (no separators) in the output after a header containing some info. 

I'm afraid that if you pad the strings, you won't find any matches because the padding character does not appear anywhere in the text. The patterns have to be of the same length. Pizza&Chili, as my r-index code, have been designed just for benchmarking purposes so it was not very important to allow for different pattern lengths in the input format.
